// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/magarantline/AdminDashboard.tsx": () => import("../components/mockups/magarantline/AdminDashboard.tsx"),
  "./components/mockups/magarantline/HomePage.tsx": () => import("../components/mockups/magarantline/HomePage.tsx"),
  "./components/mockups/magarantline/Leaderboard.tsx": () => import("../components/mockups/magarantline/Leaderboard.tsx"),
  "./components/mockups/magarantline/LeaveARant.tsx": () => import("../components/mockups/magarantline/LeaveARant.tsx"),
  "./components/mockups/magarantline/RantsFeed.tsx": () => import("../components/mockups/magarantline/RantsFeed.tsx")
};
